#drop table countries;

create table countries
(
	id integer primary key,
	shortname varchar(2),
	name varchar(150),
	phonecode integer
);

insert into countries (id, shortname, name, phonecode) values (1, 'AF', 'Afghanistan', 93);
insert into countries (id, shortname, name, phonecode) values (2, 'AL', 'Albania', 355);
insert into countries (id, shortname, name, phonecode) values (3, 'DZ', 'Algeria', 213);
insert into countries (id, shortname, name, phonecode) values (4, 'AS', 'American Samoa', 1684);
insert into countries (id, shortname, name, phonecode) values (5, 'AD', 'Andorra', 376);
insert into countries (id, shortname, name, phonecode) values (6, 'AO', 'Angola', 244);
insert into countries (id, shortname, name, phonecode) values (7, 'AI', 'Anguilla', 1264);
insert into countries (id, shortname, name, phonecode) values (8, 'AQ', 'Antarctica', 0);
insert into countries (id, shortname, name, phonecode) values (9, 'AG', 'Antigua And Barbuda', 1268);
insert into countries (id, shortname, name, phonecode) values (10, 'AR', 'Argentina', 54);
insert into countries (id, shortname, name, phonecode) values (11, 'AM', 'Armenia', 374);
insert into countries (id, shortname, name, phonecode) values (12, 'AW', 'Aruba', 297);
insert into countries (id, shortname, name, phonecode) values (13, 'AU', 'Australia', 61);
insert into countries (id, shortname, name, phonecode) values (14, 'AT', 'Austria', 43);
insert into countries (id, shortname, name, phonecode) values (15, 'AZ', 'Azerbaijan', 994);
insert into countries (id, shortname, name, phonecode) values (16, 'BS', 'Bahamas The', 1242);
insert into countries (id, shortname, name, phonecode) values (17, 'BH', 'Bahrain', 973);
insert into countries (id, shortname, name, phonecode) values (18, 'BD', 'Bangladesh', 880);
insert into countries (id, shortname, name, phonecode) values (19, 'BB', 'Barbados', 1246);
insert into countries (id, shortname, name, phonecode) values (20, 'BY', 'Belarus', 375);
insert into countries (id, shortname, name, phonecode) values (21, 'BE', 'Belgium', 32);
insert into countries (id, shortname, name, phonecode) values (22, 'BZ', 'Belize', 501);
insert into countries (id, shortname, name, phonecode) values (23, 'BJ', 'Benin', 229);
insert into countries (id, shortname, name, phonecode) values (24, 'BM', 'Bermuda', 1441);
insert into countries (id, shortname, name, phonecode) values (25, 'BT', 'Bhutan', 975);
insert into countries (id, shortname, name, phonecode) values (26, 'BO', 'Bolivia', 591);
insert into countries (id, shortname, name, phonecode) values (27, 'BA', 'Bosnia and Herzegovina', 387);
insert into countries (id, shortname, name, phonecode) values (28, 'BW', 'Botswana', 267);
insert into countries (id, shortname, name, phonecode) values (29, 'BV', 'Bouvet Island', 0);
insert into countries (id, shortname, name, phonecode) values (30, 'BR', 'Brazil', 55);
insert into countries (id, shortname, name, phonecode) values (31, 'IO', 'British Indian Ocean Territory', 246);
insert into countries (id, shortname, name, phonecode) values (32, 'BN', 'Brunei', 673);
insert into countries (id, shortname, name, phonecode) values (33, 'BG', 'Bulgaria', 359);
insert into countries (id, shortname, name, phonecode) values (34, 'BF', 'Burkina Faso', 226);
insert into countries (id, shortname, name, phonecode) values (35, 'BI', 'Burundi', 257);
insert into countries (id, shortname, name, phonecode) values (36, 'KH', 'Cambodia', 855);
insert into countries (id, shortname, name, phonecode) values (37, 'CM', 'Cameroon', 237);
insert into countries (id, shortname, name, phonecode) values (38, 'CA', 'Canada', 1);
insert into countries (id, shortname, name, phonecode) values (39, 'CV', 'Cape Verde', 238);
insert into countries (id, shortname, name, phonecode) values (40, 'KY', 'Cayman Islands', 1345);
insert into countries (id, shortname, name, phonecode) values (41, 'CF', 'Central African Republic', 236);
insert into countries (id, shortname, name, phonecode) values (42, 'TD', 'Chad', 235);
insert into countries (id, shortname, name, phonecode) values (43, 'CL', 'Chile', 56);
insert into countries (id, shortname, name, phonecode) values (44, 'CN', 'China', 86);
insert into countries (id, shortname, name, phonecode) values (45, 'CX', 'Christmas Island', 61);
insert into countries (id, shortname, name, phonecode) values (46, 'CC', 'Cocos insert into countries (id, shortname, name, phonecode) values (Keeling) Islands', 672);
insert into countries (id, shortname, name, phonecode) values (47, 'CO', 'Colombia', 57);
insert into countries (id, shortname, name, phonecode) values (48, 'KM', 'Comoros', 269);
insert into countries (id, shortname, name, phonecode) values (49, 'CG', 'Congo', 242);
insert into countries (id, shortname, name, phonecode) values (50, 'CD', 'Congo The Democratic Republic Of The', 242);
insert into countries (id, shortname, name, phonecode) values (51, 'CK', 'Cook Islands', 682);
insert into countries (id, shortname, name, phonecode) values (52, 'CR', 'Costa Rica', 506);
insert into countries (id, shortname, name, phonecode) values (53, 'CI', 'Cote D''Ivoire insert into countries (id, shortname, name, phonecode) values (Ivory Coast)', 225);
insert into countries (id, shortname, name, phonecode) values (54, 'HR', 'Croatia insert into countries (id, shortname, name, phonecode) values (Hrvatska)', 385);
insert into countries (id, shortname, name, phonecode) values (55, 'CU', 'Cuba', 53);
insert into countries (id, shortname, name, phonecode) values (56, 'CY', 'Cyprus', 357);
insert into countries (id, shortname, name, phonecode) values (57, 'CZ', 'Czech Republic', 420);
insert into countries (id, shortname, name, phonecode) values (58, 'DK', 'Denmark', 45);
insert into countries (id, shortname, name, phonecode) values (59, 'DJ', 'Djibouti', 253);
insert into countries (id, shortname, name, phonecode) values (60, 'DM', 'Dominica', 1767);
insert into countries (id, shortname, name, phonecode) values (61, 'DO', 'Dominican Republic', 1809);
insert into countries (id, shortname, name, phonecode) values (62, 'TP', 'East Timor', 670);
insert into countries (id, shortname, name, phonecode) values (63, 'EC', 'Ecuador', 593);
insert into countries (id, shortname, name, phonecode) values (64, 'EG', 'Egypt', 20);
insert into countries (id, shortname, name, phonecode) values (65, 'SV', 'El Salvador', 503);
insert into countries (id, shortname, name, phonecode) values (66, 'GQ', 'Equatorial Guinea', 240);
insert into countries (id, shortname, name, phonecode) values (67, 'ER', 'Eritrea', 291);
insert into countries (id, shortname, name, phonecode) values (68, 'EE', 'Estonia', 372);
insert into countries (id, shortname, name, phonecode) values (69, 'ET', 'Ethiopia', 251);
insert into countries (id, shortname, name, phonecode) values (70, 'XA', 'External Territories of Australia', 61);
insert into countries (id, shortname, name, phonecode) values (71, 'FK', 'Falkland Islands', 500);
insert into countries (id, shortname, name, phonecode) values (72, 'FO', 'Faroe Islands', 298);
insert into countries (id, shortname, name, phonecode) values (73, 'FJ', 'Fiji Islands', 679);
insert into countries (id, shortname, name, phonecode) values (74, 'FI', 'Finland', 358);
insert into countries (id, shortname, name, phonecode) values (75, 'FR', 'France', 33);
insert into countries (id, shortname, name, phonecode) values (76, 'GF', 'French Guiana', 594);
insert into countries (id, shortname, name, phonecode) values (77, 'PF', 'French Polynesia', 689);
insert into countries (id, shortname, name, phonecode) values (78, 'TF', 'French Southern Territories', 0);
insert into countries (id, shortname, name, phonecode) values (79, 'GA', 'Gabon', 241);
insert into countries (id, shortname, name, phonecode) values (80, 'GM', 'Gambia The', 220);
insert into countries (id, shortname, name, phonecode) values (81, 'GE', 'Georgia', 995);
insert into countries (id, shortname, name, phonecode) values (82, 'DE', 'Germany', 49);
insert into countries (id, shortname, name, phonecode) values (83, 'GH', 'Ghana', 233);
insert into countries (id, shortname, name, phonecode) values (84, 'GI', 'Gibraltar', 350);
insert into countries (id, shortname, name, phonecode) values (85, 'GR', 'Greece', 30);
insert into countries (id, shortname, name, phonecode) values (86, 'GL', 'Greenland', 299);
insert into countries (id, shortname, name, phonecode) values (87, 'GD', 'Grenada', 1473);
insert into countries (id, shortname, name, phonecode) values (88, 'GP', 'Guadeloupe', 590);
insert into countries (id, shortname, name, phonecode) values (89, 'GU', 'Guam', 1671);
insert into countries (id, shortname, name, phonecode) values (90, 'GT', 'Guatemala', 502);
insert into countries (id, shortname, name, phonecode) values (91, 'XU', 'Guernsey and Alderney', 44);
insert into countries (id, shortname, name, phonecode) values (92, 'GN', 'Guinea', 224);
insert into countries (id, shortname, name, phonecode) values (93, 'GW', 'Guinea-Bissau', 245);
insert into countries (id, shortname, name, phonecode) values (94, 'GY', 'Guyana', 592);
insert into countries (id, shortname, name, phonecode) values (95, 'HT', 'Haiti', 509);
insert into countries (id, shortname, name, phonecode) values (96, 'HM', 'Heard and McDonald Islands', 0);
insert into countries (id, shortname, name, phonecode) values (97, 'HN', 'Honduras', 504);
insert into countries (id, shortname, name, phonecode) values (98, 'HK', 'Hong Kong S.A.R.', 852);
insert into countries (id, shortname, name, phonecode) values (99, 'HU', 'Hungary', 36);
insert into countries (id, shortname, name, phonecode) values (100, 'IS', 'Iceland', 354);
insert into countries (id, shortname, name, phonecode) values (101, 'IN', 'India', 91);
insert into countries (id, shortname, name, phonecode) values (102, 'ID', 'Indonesia', 62);
insert into countries (id, shortname, name, phonecode) values (103, 'IR', 'Iran', 98);
insert into countries (id, shortname, name, phonecode) values (104, 'IQ', 'Iraq', 964);
insert into countries (id, shortname, name, phonecode) values (105, 'IE', 'Ireland', 353);
insert into countries (id, shortname, name, phonecode) values (106, 'IL', 'Israel', 972);
insert into countries (id, shortname, name, phonecode) values (107, 'IT', 'Italy', 39);
insert into countries (id, shortname, name, phonecode) values (108, 'JM', 'Jamaica', 1876);
insert into countries (id, shortname, name, phonecode) values (109, 'JP', 'Japan', 81);
insert into countries (id, shortname, name, phonecode) values (110, 'XJ', 'Jersey', 44);
insert into countries (id, shortname, name, phonecode) values (111, 'JO', 'Jordan', 962);
insert into countries (id, shortname, name, phonecode) values (112, 'KZ', 'Kazakhstan', 7);
insert into countries (id, shortname, name, phonecode) values (113, 'KE', 'Kenya', 254);
insert into countries (id, shortname, name, phonecode) values (114, 'KI', 'Kiribati', 686);
insert into countries (id, shortname, name, phonecode) values (115, 'KP', 'Korea North', 850);
insert into countries (id, shortname, name, phonecode) values (116, 'KR', 'Korea South', 82);
insert into countries (id, shortname, name, phonecode) values (117, 'KW', 'Kuwait', 965);
insert into countries (id, shortname, name, phonecode) values (118, 'KG', 'Kyrgyzstan', 996);
insert into countries (id, shortname, name, phonecode) values (119, 'LA', 'Laos', 856);
insert into countries (id, shortname, name, phonecode) values (120, 'LV', 'Latvia', 371);
insert into countries (id, shortname, name, phonecode) values (121, 'LB', 'Lebanon', 961);
insert into countries (id, shortname, name, phonecode) values (122, 'LS', 'Lesotho', 266);
insert into countries (id, shortname, name, phonecode) values (123, 'LR', 'Liberia', 231);
insert into countries (id, shortname, name, phonecode) values (124, 'LY', 'Libya', 218);
insert into countries (id, shortname, name, phonecode) values (125, 'LI', 'Liechtenstein', 423);
insert into countries (id, shortname, name, phonecode) values (126, 'LT', 'Lithuania', 370);
insert into countries (id, shortname, name, phonecode) values (127, 'LU', 'Luxembourg', 352);
insert into countries (id, shortname, name, phonecode) values (128, 'MO', 'Macau S.A.R.', 853);
insert into countries (id, shortname, name, phonecode) values (129, 'MK', 'Macedonia', 389);
insert into countries (id, shortname, name, phonecode) values (130, 'MG', 'Madagascar', 261);
insert into countries (id, shortname, name, phonecode) values (131, 'MW', 'Malawi', 265);
insert into countries (id, shortname, name, phonecode) values (132, 'MY', 'Malaysia', 60);
insert into countries (id, shortname, name, phonecode) values (133, 'MV', 'Maldives', 960);
insert into countries (id, shortname, name, phonecode) values (134, 'ML', 'Mali', 223);
insert into countries (id, shortname, name, phonecode) values (135, 'MT', 'Malta', 356);
insert into countries (id, shortname, name, phonecode) values (136, 'XM', 'Man insert into countries (id, shortname, name, phonecode) values (Isle of)', 44);
insert into countries (id, shortname, name, phonecode) values (137, 'MH', 'Marshall Islands', 692);
insert into countries (id, shortname, name, phonecode) values (138, 'MQ', 'Martinique', 596);
insert into countries (id, shortname, name, phonecode) values (139, 'MR', 'Mauritania', 222);
insert into countries (id, shortname, name, phonecode) values (140, 'MU', 'Mauritius', 230);
insert into countries (id, shortname, name, phonecode) values (141, 'YT', 'Mayotte', 269);
insert into countries (id, shortname, name, phonecode) values (142, 'MX', 'Mexico', 52);
insert into countries (id, shortname, name, phonecode) values (143, 'FM', 'Micronesia', 691);
insert into countries (id, shortname, name, phonecode) values (144, 'MD', 'Moldova', 373);
insert into countries (id, shortname, name, phonecode) values (145, 'MC', 'Monaco', 377);
insert into countries (id, shortname, name, phonecode) values (146, 'MN', 'Mongolia', 976);
insert into countries (id, shortname, name, phonecode) values (147, 'MS', 'Montserrat', 1664);
insert into countries (id, shortname, name, phonecode) values (148, 'MA', 'Morocco', 212);
insert into countries (id, shortname, name, phonecode) values (149, 'MZ', 'Mozambique', 258);
insert into countries (id, shortname, name, phonecode) values (150, 'MM', 'Myanmar', 95);
insert into countries (id, shortname, name, phonecode) values (151, 'NA', 'Namibia', 264);
insert into countries (id, shortname, name, phonecode) values (152, 'NR', 'Nauru', 674);
insert into countries (id, shortname, name, phonecode) values (153, 'NP', 'Nepal', 977);
insert into countries (id, shortname, name, phonecode) values (154, 'AN', 'Netherlands Antilles', 599);
insert into countries (id, shortname, name, phonecode) values (155, 'NL', 'Netherlands The', 31);
insert into countries (id, shortname, name, phonecode) values (156, 'NC', 'New Caledonia', 687);
insert into countries (id, shortname, name, phonecode) values (157, 'NZ', 'New Zealand', 64);
insert into countries (id, shortname, name, phonecode) values (158, 'NI', 'Nicaragua', 505);
insert into countries (id, shortname, name, phonecode) values (159, 'NE', 'Niger', 227);
insert into countries (id, shortname, name, phonecode) values (160, 'NG', 'Nigeria', 234);
insert into countries (id, shortname, name, phonecode) values (161, 'NU', 'Niue', 683);
insert into countries (id, shortname, name, phonecode) values (162, 'NF', 'Norfolk Island', 672);
insert into countries (id, shortname, name, phonecode) values (163, 'MP', 'Northern Mariana Islands', 1670);
insert into countries (id, shortname, name, phonecode) values (164, 'NO', 'Norway', 47);
insert into countries (id, shortname, name, phonecode) values (165, 'OM', 'Oman', 968);
insert into countries (id, shortname, name, phonecode) values (166, 'PK', 'Pakistan', 92);
insert into countries (id, shortname, name, phonecode) values (167, 'PW', 'Palau', 680);
insert into countries (id, shortname, name, phonecode) values (168, 'PS', 'Palestinian Territory Occupied', 970);
insert into countries (id, shortname, name, phonecode) values (169, 'PA', 'Panama', 507);
insert into countries (id, shortname, name, phonecode) values (170, 'PG', 'Papua new Guinea', 675);
insert into countries (id, shortname, name, phonecode) values (171, 'PY', 'Paraguay', 595);
insert into countries (id, shortname, name, phonecode) values (172, 'PE', 'Peru', 51);
insert into countries (id, shortname, name, phonecode) values (173, 'PH', 'Philippines', 63);
insert into countries (id, shortname, name, phonecode) values (174, 'PN', 'Pitcairn Island', 0);
insert into countries (id, shortname, name, phonecode) values (175, 'PL', 'Poland', 48);
insert into countries (id, shortname, name, phonecode) values (176, 'PT', 'Portugal', 351);
insert into countries (id, shortname, name, phonecode) values (177, 'PR', 'Puerto Rico', 1787);
insert into countries (id, shortname, name, phonecode) values (178, 'QA', 'Qatar', 974);
insert into countries (id, shortname, name, phonecode) values (179, 'RE', 'Reunion', 262);
insert into countries (id, shortname, name, phonecode) values (180, 'RO', 'Romania', 40);
insert into countries (id, shortname, name, phonecode) values (181, 'RU', 'Russia', 70);
insert into countries (id, shortname, name, phonecode) values (182, 'RW', 'Rwanda', 250);
insert into countries (id, shortname, name, phonecode) values (183, 'SH', 'Saint Helena', 290);
insert into countries (id, shortname, name, phonecode) values (184, 'KN', 'Saint Kitts And Nevis', 1869);
insert into countries (id, shortname, name, phonecode) values (185, 'LC', 'Saint Lucia', 1758);
insert into countries (id, shortname, name, phonecode) values (186, 'PM', 'Saint Pierre and Miquelon', 508);
insert into countries (id, shortname, name, phonecode) values (187, 'VC', 'Saint Vincent And The Grenadines', 1784);
insert into countries (id, shortname, name, phonecode) values (188, 'WS', 'Samoa', 684);
insert into countries (id, shortname, name, phonecode) values (189, 'SM', 'San Marino', 378);
insert into countries (id, shortname, name, phonecode) values (190, 'ST', 'Sao Tome and Principe', 239);
insert into countries (id, shortname, name, phonecode) values (191, 'SA', 'Saudi Arabia', 966);
insert into countries (id, shortname, name, phonecode) values (192, 'SN', 'Senegal', 221);
insert into countries (id, shortname, name, phonecode) values (193, 'RS', 'Serbia', 381);
insert into countries (id, shortname, name, phonecode) values (194, 'SC', 'Seychelles', 248);
insert into countries (id, shortname, name, phonecode) values (195, 'SL', 'Sierra Leone', 232);
insert into countries (id, shortname, name, phonecode) values (196, 'SG', 'Singapore', 65);
insert into countries (id, shortname, name, phonecode) values (197, 'SK', 'Slovakia', 421);
insert into countries (id, shortname, name, phonecode) values (198, 'SI', 'Slovenia', 386);
insert into countries (id, shortname, name, phonecode) values (199, 'XG', 'Smaller Territories of the UK', 44);
insert into countries (id, shortname, name, phonecode) values (200, 'SB', 'Solomon Islands', 677);
insert into countries (id, shortname, name, phonecode) values (201, 'SO', 'Somalia', 252);
insert into countries (id, shortname, name, phonecode) values (202, 'ZA', 'South Africa', 27);
insert into countries (id, shortname, name, phonecode) values (203, 'GS', 'South Georgia', 0);
insert into countries (id, shortname, name, phonecode) values (204, 'SS', 'South Sudan', 211);
insert into countries (id, shortname, name, phonecode) values (205, 'ES', 'Spain', 34);
insert into countries (id, shortname, name, phonecode) values (206, 'LK', 'Sri Lanka', 94);
insert into countries (id, shortname, name, phonecode) values (207, 'SD', 'Sudan', 249);
insert into countries (id, shortname, name, phonecode) values (208, 'SR', 'Suriname', 597);
insert into countries (id, shortname, name, phonecode) values (209, 'SJ', 'Svalbard And Jan Mayen Islands', 47);
insert into countries (id, shortname, name, phonecode) values (210, 'SZ', 'Swaziland', 268);
insert into countries (id, shortname, name, phonecode) values (211, 'SE', 'Sweden', 46);
insert into countries (id, shortname, name, phonecode) values (212, 'CH', 'Switzerland', 41);
insert into countries (id, shortname, name, phonecode) values (213, 'SY', 'Syria', 963);
insert into countries (id, shortname, name, phonecode) values (214, 'TW', 'Taiwan', 886);
insert into countries (id, shortname, name, phonecode) values (215, 'TJ', 'Tajikistan', 992);
insert into countries (id, shortname, name, phonecode) values (216, 'TZ', 'Tanzania', 255);
insert into countries (id, shortname, name, phonecode) values (217, 'TH', 'Thailand', 66);
insert into countries (id, shortname, name, phonecode) values (218, 'TG', 'Togo', 228);
insert into countries (id, shortname, name, phonecode) values (219, 'TK', 'Tokelau', 690);
insert into countries (id, shortname, name, phonecode) values (220, 'TO', 'Tonga', 676);
insert into countries (id, shortname, name, phonecode) values (221, 'TT', 'Trinidad And Tobago', 1868);
insert into countries (id, shortname, name, phonecode) values (222, 'TN', 'Tunisia', 216);
insert into countries (id, shortname, name, phonecode) values (223, 'TR', 'Turkey', 90);
insert into countries (id, shortname, name, phonecode) values (224, 'TM', 'Turkmenistan', 7370);
insert into countries (id, shortname, name, phonecode) values (225, 'TC', 'Turks And Caicos Islands', 1649);
insert into countries (id, shortname, name, phonecode) values (226, 'TV', 'Tuvalu', 688);
insert into countries (id, shortname, name, phonecode) values (227, 'UG', 'Uganda', 256);
insert into countries (id, shortname, name, phonecode) values (228, 'UA', 'Ukraine', 380);
insert into countries (id, shortname, name, phonecode) values (229, 'AE', 'United Arab Emirates', 971);
insert into countries (id, shortname, name, phonecode) values (230, 'GB', 'United Kingdom', 44);
insert into countries (id, shortname, name, phonecode) values (231, 'US', 'United States', 1);
insert into countries (id, shortname, name, phonecode) values (232, 'UM', 'United States Minor Outlying Islands', 1);
insert into countries (id, shortname, name, phonecode) values (233, 'UY', 'Uruguay', 598);
insert into countries (id, shortname, name, phonecode) values (234, 'UZ', 'Uzbekistan', 998);
insert into countries (id, shortname, name, phonecode) values (235, 'VU', 'Vanuatu', 678);
insert into countries (id, shortname, name, phonecode) values (236, 'VA', 'Vatican City State insert into countries (id, shortname, name, phonecode) values (Holy See)', 39);
insert into countries (id, shortname, name, phonecode) values (237, 'VE', 'Venezuela', 58);
insert into countries (id, shortname, name, phonecode) values (238, 'VN', 'Vietnam', 84);
insert into countries (id, shortname, name, phonecode) values (239, 'VG', 'Virgin Islands insert into countries (id, shortname, name, phonecode) values (British)', 1284);
insert into countries (id, shortname, name, phonecode) values (240, 'VI', 'Virgin Islands insert into countries (id, shortname, name, phonecode) values (US)', 1340);
insert into countries (id, shortname, name, phonecode) values (241, 'WF', 'Wallis And Futuna Islands', 681);
insert into countries (id, shortname, name, phonecode) values (242, 'EH', 'Western Sahara', 212);
insert into countries (id, shortname, name, phonecode) values (243, 'YE', 'Yemen', 967);
insert into countries (id, shortname, name, phonecode) values (244, 'YU', 'Yugoslavia', 38);
insert into countries (id, shortname, name, phonecode) values (245, 'ZM', 'Zambia', 260);
insert into countries (id, shortname, name, phonecode) values (246, 'ZW', 'Zimbabwe', 263);
commit;